title : SMIT HARESHKUMAR RANA
logo : /assests/img/dp.gif
description : Highly motivated recent graduate seeking growth in an Entry Level Data Analyst position. Committed to delivering precise results through rigorous evaluations with expertise in Python, SQL, R, Excel, Power BI, and Tableau. Seeking a detail-oriented data team to advance analytical proficiency and ready to excel in a dynamic data-driven environment. 
theme: jekyll-theme-minimal
show_downloads: false
hide_downloads : true
download_rmd: false
